services:
  - type: web
    name: sistema-comedor-prize
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "1"
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
