services:
  - type: web
    name: comedor-prize-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENABLE_ADMIN_USER_ALERTS
        value: "0"
      - key: ADMIN_AUDIT_EMAIL
        value: omar.azabache24@gmail.com
